ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "isBackend" BOOLEAN;
ALTER TABLE "Deployment" ADD COLUMN IF NOT EXISTS "isBackend" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Deployment" ADD COLUMN IF NOT EXISTS "ecrImageUri" TEXT;
