'use strict';
/**
 * nginxConfigService.js
 *
 * Generates and manages per-project nginx reverse-proxy config files.
 * Called after every successful backend (EC2) deployment.
 *
 * Architecture — TWO MODES
 * ────────────────────────
 * The nginx binary does NOT exist bare on the EC2 host. nginx runs as a
 * Docker container. This service handles two deployment topologies:
 *
 * Mode A — NGINX_CONTAINER_NAME is set (nginx Docker container on EC2 host)
 * ──────────────────────────────────────────────────────────────────────────
 *   SSM writes the conf file to NGINX_CONF_HOST_DIR (a host directory
 *   bind-mounted into the nginx container at /etc/nginx/conf.d/projects),
 *   then reloads nginx via:
 *     docker exec <NGINX_CONTAINER_NAME> nginx -s reload
 *
 *   Required env vars:
 *     NGINX_CONTAINER_NAME   nginx container name, e.g. "deployhub-nginx-1"
 *     NGINX_CONF_HOST_DIR    host-side bind-mount path (default: /opt/deployhub/nginx/conf.d/projects)
 *
 * Mode B — NGINX_CONTAINER_NAME is NOT set  (default / current setup)
 * ────────────────────────────────────────────────────────────────────
 *   Each deployed container is directly reachable at EC2_PUBLIC_DNS:hostPort.
 *   No nginx is involved on the EC2 host — the direct URL is returned as-is
 *   and no SSM reload command is issued. This is the correct behaviour for
 *   the current architecture where each project gets its own unique port.
 *
 * The final previewUrl is always: http://<EC2_PUBLIC_DNS>:<hostPort>
 */

const { SSMClient, SendCommandCommand, GetCommandInvocationCommand } = require('@aws-sdk/client-ssm');
const { logger } = require('../utils/logger');

const REGION = process.env.AWS_REGION || 'us-east-1';
const ssm    = new SSMClient({ region: REGION });

// Name of the nginx Docker container on the EC2 host.
// Leave unset (default) to skip nginx management entirely — containers are
// accessed directly via EC2_PUBLIC_DNS:hostPort.
const NGINX_CONTAINER_NAME = process.env.NGINX_CONTAINER_NAME || '';

// Host directory bind-mounted into the nginx container at /etc/nginx/conf.d/projects.
// Only used when NGINX_CONTAINER_NAME is set.
const NGINX_CONF_HOST_DIR = process.env.NGINX_CONF_HOST_DIR || '/opt/deployhub/nginx/conf.d/projects';

// Path INSIDE the nginx container where per-project confs live.
const NGINX_PROJECTS_CONTAINER_DIR = '/etc/nginx/conf.d/projects';

// ── Nginx config block generator ─────────────────────────────────────────────

/**
 * Build the nginx server-block config text for one backend project.
 *
 * @param {object} opts
 * @param {string} opts.projectId
 * @param {string} opts.deploymentId
 * @param {number} opts.hostPort       – unique EC2 host-side port for this project
 * @param {number} opts.containerPort  – port the app listens on inside Docker
 * @param {string} opts.publicDns      – EC2 public DNS hostname
 * @returns {string}  nginx config block text
 */
function buildNginxConfBlock({ projectId, deploymentId, hostPort, containerPort, publicDns }) {
  // Sanitise projectId for use as an nginx upstream name (replace hyphens)
  const upstreamName = `deployhub_${projectId.replace(/[^a-zA-Z0-9]/g, '_')}`;

  return [
    `# Auto-generated by DeployHub — DO NOT EDIT`,
    `# project:    ${projectId}`,
    `# deployment: ${deploymentId}`,
    `# updated:    ${new Date().toISOString()}`,
    `#`,
    `# Traffic:  client -> http://${publicDns}:${hostPort}`,
    `#           nginx  -> 127.0.0.1:${hostPort} (Docker, internal port ${containerPort})`,
    ``,
    `upstream ${upstreamName} {`,
    `  server 127.0.0.1:${hostPort};`,
    `  keepalive 8;`,
    `}`,
    ``,
    `server {`,
    `  listen ${hostPort};`,
    `  server_name _;`,
    ``,
    `  proxy_read_timeout    120s;`,
    `  proxy_send_timeout    120s;`,
    `  proxy_connect_timeout  10s;`,
    ``,
    `  location / {`,
    `    proxy_pass         http://${upstreamName};`,
    `    proxy_http_version 1.1;`,
    `    proxy_set_header   Host              $host;`,
    `    proxy_set_header   X-Real-IP         $remote_addr;`,
    `    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;`,
    `    proxy_set_header   X-Forwarded-Proto $scheme;`,
    `    proxy_set_header   Upgrade           $http_upgrade;`,
    `    proxy_set_header   Connection        "upgrade";`,
    `    add_header         X-DeployHub-Project    "${projectId}" always;`,
    `    add_header         X-DeployHub-Deployment "${deploymentId}" always;`,
    `  }`,
    ``,
    `  location /_deployhub/health {`,
    `    access_log off;`,
    `    return 200 '{"ok":true,"project":"${projectId}","port":${hostPort}}';`,
    `    add_header Content-Type application/json;`,
    `  }`,
    `}`,
    ``,
  ].join('\n');
}

// ── SSM helpers ───────────────────────────────────────────────────────────────

async function runSsmCommand(instanceId, script, timeoutSeconds = 60) {
  const sendRes = await ssm.send(new SendCommandCommand({
    InstanceIds:    [instanceId],
    DocumentName:   'AWS-RunShellScript',
    Parameters:     { commands: [script] },
    TimeoutSeconds: timeoutSeconds,
  }));

  const commandId = sendRes.Command.CommandId;
  const deadline  = Date.now() + timeoutSeconds * 1000;

  while (Date.now() < deadline) {
    await new Promise(r => setTimeout(r, 2000));
    const inv = await ssm.send(new GetCommandInvocationCommand({
      CommandId:  commandId,
      InstanceId: instanceId,
    })).catch(() => null);

    if (!inv) continue;

    if (inv.Status === 'Success') {
      return { ok: true, stdout: inv.StandardOutputContent || '', stderr: inv.StandardErrorContent || '' };
    }
    if (['Failed', 'Cancelled', 'TimedOut'].includes(inv.Status)) {
      return { ok: false, stdout: inv.StandardOutputContent || '', stderr: inv.StandardErrorContent || inv.StatusDetails || inv.Status };
    }
  }

  return { ok: false, stdout: '', stderr: 'SSM command timed out waiting for result' };
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Register a new backend deployment with nginx (Mode A) or skip (Mode B).
 *
 * Mode A (NGINX_CONTAINER_NAME set):
 *   Writes conf to the host bind-mount dir, then does `docker exec nginx -s reload`.
 *
 * Mode B (NGINX_CONTAINER_NAME not set — current default):
 *   Skips nginx entirely. Containers are reachable directly at EC2:hostPort.
 *   Logs a clear info message so the non-action is visible in build logs.
 *
 * @returns {Promise<string>}  The public URL for this backend project
 */
async function registerBackendWithNginx({ instanceId, projectId, deploymentId, hostPort, containerPort, publicDns, log }) {
  const publicUrl = `http://${publicDns}:${hostPort}`;

  // ── Mode B: No nginx container configured — skip silently ─────────────────
  if (!NGINX_CONTAINER_NAME) {
    log(`ℹ️  NGINX_CONTAINER_NAME not set — skipping nginx registration`);
    log(`🌐 Backend accessible directly at: ${publicUrl}`);
    return publicUrl;
  }

  // ── Mode A: nginx runs as Docker container on EC2 host ────────────────────
  const confPath = `${NGINX_CONF_HOST_DIR}/project-${projectId}.conf`;
  const confBlock = buildNginxConfBlock({ projectId, deploymentId, hostPort, containerPort, publicDns });

  // We use a Python heredoc writer to avoid bash quoting issues with nginx $vars
  const script = `
set -e

# 1. Ensure host-side conf directory exists (bind-mounted into nginx container)
mkdir -p "${NGINX_CONF_HOST_DIR}"

# 2. Write conf file using Python to avoid bash quoting issues with nginx $ vars
python3 -c "
import sys
conf = sys.argv[1]
with open('${confPath}', 'w') as f:
    f.write(conf)
print('Wrote ${confPath}')
" ${JSON.stringify(confBlock)}

# 3. Validate config inside the nginx container
echo "Testing nginx config..."
docker exec ${NGINX_CONTAINER_NAME} nginx -t 2>&1

# 4. Reload nginx inside the container (zero-downtime)
docker exec ${NGINX_CONTAINER_NAME} nginx -s reload
echo "nginx reloaded — project ${projectId} live on port ${hostPort}"
`;

  log(`📝 Writing nginx config for project ${projectId} (port ${hostPort})...`);

  const result = await runSsmCommand(instanceId, script, 60);

  if (result.ok) {
    if (result.stdout) log(result.stdout.trim());
    log(`✓ nginx registered — ${publicUrl}`);
  } else {
    // Non-fatal: the container is still running on hostPort directly.
    // Log the warning but don't fail the deployment.
    log(`⚠️  nginx reload failed (container still accessible directly): ${result.stderr}`);
    logger.warn(`[nginx] registerBackendWithNginx failed for ${projectId}: ${result.stderr}`);
  }

  return publicUrl;
}

/**
 * Remove a project's nginx conf and reload.
 * Called when a project is deleted.
 * Safe to call even when NGINX_CONTAINER_NAME is not set.
 */
async function deregisterBackendFromNginx({ instanceId, projectId, log = () => {} }) {
  if (!NGINX_CONTAINER_NAME) {
    logger.debug(`[nginx] NGINX_CONTAINER_NAME not set — skipping deregister for ${projectId}`);
    return;
  }

  const confPath = `${NGINX_CONF_HOST_DIR}/project-${projectId}.conf`;

  const script = `
set -e
if [ -f "${confPath}" ]; then
  rm -f "${confPath}"
  echo "Removed ${confPath}"
  docker exec ${NGINX_CONTAINER_NAME} nginx -t 2>&1 && docker exec ${NGINX_CONTAINER_NAME} nginx -s reload
  echo "nginx reloaded"
else
  echo "No conf found for project ${projectId} — nothing to remove"
fi
`;

  log(`🗑️  Removing nginx config for project ${projectId}...`);

  try {
    const result = await runSsmCommand(instanceId, script, 30);
    if (result.stdout) log(result.stdout.trim());
    if (!result.ok) logger.warn(`[nginx] deregister failed for ${projectId}: ${result.stderr}`);
  } catch (err) {
    logger.warn(`[nginx] deregisterBackendFromNginx error for ${projectId}: ${err.message}`);
  }
}

/**
 * Re-sync ALL active backend projects to nginx in one shot.
 * Useful after nginx container restarts that wipe conf.d/projects/.
 * Safe no-op when NGINX_CONTAINER_NAME is not set.
 */
async function syncAllBackendsToNginx({ instanceId, projects, publicDns, log = () => {} }) {
  if (!NGINX_CONTAINER_NAME) {
    log('ℹ️  NGINX_CONTAINER_NAME not set — nginx sync skipped (direct port access in use)');
    return;
  }

  if (projects.length === 0) {
    log('ℹ️  No active backend projects to sync');
    return;
  }

  log(`🔄 Syncing ${projects.length} backend project(s) to nginx container ${NGINX_CONTAINER_NAME}...`);

  // Write all conf files then do a single reload
  const writes = projects.map(({ projectId, deploymentId, hostPort, containerPort }) => {
    const confPath  = `${NGINX_CONF_HOST_DIR}/project-${projectId}.conf`;
    const confBlock = buildNginxConfBlock({ projectId, deploymentId, hostPort, containerPort, publicDns });
    // Use python3 to write each file to avoid bash heredoc quoting problems
    return `python3 -c "import sys; open('${confPath}','w').write(sys.argv[1])" ${JSON.stringify(confBlock)} && echo "  wrote ${confPath}"`;
  }).join('\n');

  const script = `
set -e
mkdir -p "${NGINX_CONF_HOST_DIR}"
${writes}
echo "All conf files written (${projects.length} projects)"
docker exec ${NGINX_CONTAINER_NAME} nginx -t 2>&1
docker exec ${NGINX_CONTAINER_NAME} nginx -s reload
echo "nginx reloaded with ${projects.length} project(s)"
`;

  try {
    const result = await runSsmCommand(instanceId, script, 60);
    if (result.stdout) log(result.stdout.trim());
    if (result.ok) {
      log(`✓ nginx sync complete`);
    } else {
      logger.warn(`[nginx] syncAllBackendsToNginx failed: ${result.stderr}`);
    }
  } catch (err) {
    logger.warn(`[nginx] syncAllBackendsToNginx error: ${err.message}`);
  }
}

module.exports = {
  buildNginxConfBlock,
  registerBackendWithNginx,
  deregisterBackendFromNginx,
  syncAllBackendsToNginx,
};